image: gcc

test:
  stage: test
  before_script: 
    - apt-get update -qq
    - apt-get install -qq libtalloc-dev uthash-dev libarchive-dev gdb strace realpath 
  script: 
    - make -C src loader.exe loader-m32.exe build.h
    - make -C src proot 
    - make -C tests
  artifacts:
    paths:
      - src
